apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment # name of deployment
spec:
  replicas: 1 # how many pods will be created?
  selector:
    matchLabels:
      component: web # how will i find this pod in the future?
  template:
    metadata:
      labels:
        component: web # attached label for future administaration
    spec:
      containers:
        - name: client # name of the container
          image: stephengrider/multi-client # where to get the image from
          ports:
            - containerPort: 3000 # ports exposed inside the pod
    resources:
